// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWYVursRFcisNjBjjwBB-HtZ0sYcPkdvA',
    appId: '1:1024116935518:web:5851303b1b77dee5fd9dcf',
    messagingSenderId: '1024116935518',
    projectId: 'classmate-849fb',
    authDomain: 'classmate-849fb.firebaseapp.com',
    storageBucket: 'classmate-849fb.appspot.com',
    measurementId: 'G-9NX4BC8LLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-9_3fJfZztkLawLoJjXwRxTnk6SqADzg',
    appId: '1:1024116935518:android:1216971ab0b8dbbefd9dcf',
    messagingSenderId: '1024116935518',
    projectId: 'classmate-849fb',
    storageBucket: 'classmate-849fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAntEUOENfFSmNeXvM_3LQeP3bImE8PGnc',
    appId: '1:1024116935518:ios:1ab8c2cb9230ec52fd9dcf',
    messagingSenderId: '1024116935518',
    projectId: 'classmate-849fb',
    storageBucket: 'classmate-849fb.appspot.com',
    iosBundleId: 'com.example.classmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAntEUOENfFSmNeXvM_3LQeP3bImE8PGnc',
    appId: '1:1024116935518:ios:1ab8c2cb9230ec52fd9dcf',
    messagingSenderId: '1024116935518',
    projectId: 'classmate-849fb',
    storageBucket: 'classmate-849fb.appspot.com',
    iosBundleId: 'com.example.classmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWYVursRFcisNjBjjwBB-HtZ0sYcPkdvA',
    appId: '1:1024116935518:web:5f4addb32f750781fd9dcf',
    messagingSenderId: '1024116935518',
    projectId: 'classmate-849fb',
    authDomain: 'classmate-849fb.firebaseapp.com',
    storageBucket: 'classmate-849fb.appspot.com',
    measurementId: 'G-3Z6ZRWWVV0',
  );
}
